# Generated by Django 4.2.6 on 2023-10-28 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Cantidad',
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disfraztalla',
            name='disfraz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='api.disfraces'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 28, 23, 33, 39, 1632, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='disfraz')),
                ('disfraz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.disfraces')),
            ],
        ),
    ]
