# Generated by Django 4.2.6 on 2023-11-06 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ventas_cantidad_ventaproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.disfraces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='Fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 6, 20, 27, 51, 513072, tzinfo=datetime.timezone.utc)),
        ),
    ]
