# Generated by Django 4.2.6 on 2023-11-11 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 11, 4, 42, 16, 992819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('disfraz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disfraztalla')),
            ],
        ),
    ]
